server:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 300m
      memory: 400Mi

  retention: "2h"

# Disable unnecessary components
alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false
