grafana:
  adminPassword: admin
  service:
    type: NodePort

  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10

  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 10

prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        memory: 400Mi
      limits:
        memory: 800Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

kube-state-metrics:
  resources:
    requests:
      memory: 100Mi

nodeExporter:
  resources:
    requests:
      memory: 50Mi
