apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/paragjo/gitops-incident-simulation
    targetRevision: HEAD
    path: gitops/base/demo-app/helm/demo-app

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-dev

  syncPolicy: {}
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
